"""Public interface for the authoritative application module."""

from boss_agent_cli.application.contracts import (
	ApplicationEvent,
	ApplicationStateSnapshot,
	CancelRunCommand,
	CommandResult,
	ConnectPlatformSessionCommand,
	CurrentStateQuery,
	DomainError,
	DomainErrorDetails,
	ErrorCode,
	InspectJobCommand,
	JobDetailView,
	JobSearchBatch,
	JobSearchGoal,
	JobSeekingState,
	JobSourceDetail,
	JobSummary,
	PlatformSessionState,
	RequestContext,
	LogoutPlatformSessionCommand,
	RunSummary,
	SetShortlistedCommand,
	StartJobSearchCommand,
	RunEventKind,
	SwitchWorkspaceCommand,
	UpdateJobSearchGoalCommand,
	WriteIntentSummary,
	WorkspaceKind,
)
from boss_agent_cli.application.module import Application, BossAdapterFailure

__all__ = [
	"Application",
	"ApplicationEvent",
	"ApplicationStateSnapshot",
	"BossAdapterFailure",
	"CancelRunCommand",
	"CommandResult",
	"ConnectPlatformSessionCommand",
	"CurrentStateQuery",
	"DomainError",
	"DomainErrorDetails",
	"ErrorCode",
	"InspectJobCommand",
	"JobDetailView",
	"JobSearchBatch",
	"JobSearchGoal",
	"JobSeekingState",
	"JobSourceDetail",
	"JobSummary",
	"PlatformSessionState",
	"RequestContext",
	"LogoutPlatformSessionCommand",
	"RunEventKind",
	"RunSummary",
	"SetShortlistedCommand",
	"StartJobSearchCommand",
	"SwitchWorkspaceCommand",
	"UpdateJobSearchGoalCommand",
	"WriteIntentSummary",
	"WorkspaceKind",
]
